services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5173:5173
    restart: always
    volumes:
      - ./frontend:/app
      - '/app/node_modules'

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8888:8888
    restart: always
    volumes:
      - ./backend:/app
      - '/app/node_modules'
  mongo:
    container_name: mongo
    image: mongo:8.0.8
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
